import type { Product, Seller, VitrineFilterConfig } from "@/ui/state/types";

export const sellers: Seller[] = [
  { 
    id: "seller-1", 
    name: "Провиант", 
    commissionRate: 0.1,
    logo: "/assets/proviant/logo.png",
    bannerUrl: "/assets/proviant/banner.png",
    rating: 4.8,
    reviewsCount: 120,
    deliveryEtaMinutes: 15,
    description: "Свежие фермерские продукты с ежедневной доставкой прямо к вашему столу."
  },
  { 
    id: "seller-2", 
    name: "Пекарня у дома", 
    commissionRate: 0.1,
    logo: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=150&q=80",
    rating: 4.7,
    reviewsCount: 85,
    deliveryEtaMinutes: 20,
    description: "Ароматный хлеб, вкусная выпечка и десерты от местных кондитеров."
  },
  { 
    id: "seller-3", 
    name: "Urban Wear", 
    commissionRate: 0.1,
    logo: "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=150&q=80",
    rating: 4.5,
    reviewsCount: 300,
    deliveryEtaMinutes: 120,
    description: "Стильная одежда и аксессуары для комфортной жизни в городе."
  },
  { 
    id: "seller-4", 
    name: "СтройИнструмент", 
    commissionRate: 0.1,
    logo: "https://images.unsplash.com/photo-1581147036324-c1e19ca9bbed?auto=format&fit=crop&w=150&q=80",
    rating: 4.6,
    reviewsCount: 50,
    deliveryEtaMinutes: 90,
    description: "Всё необходимое для ремонта и строительства по лучшим ценам."
  },
  { 
    id: "seller-5", 
    name: "Семейное кафе Кексбери", 
    commissionRate: 0.15,
    logo: "/assets/keksberi/logo.png",
    bannerUrl: "/assets/keksberi/banner.png",
    rating: 4.9,
    reviewsCount: 154,
    deliveryEtaMinutes: 45,
    description: "Уютное семейное кафе с широким выбором роллов, пиццы и бургеров. Готовим с любовью и доставляем быстро!"
  },
  { 
    id: "seller-6", 
    name: "Бургер Хаус", 
    commissionRate: 0.15,
    logo: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=150&q=80",
    bannerUrl: "/assets/burger_house/banner.png",
    rating: 4.8,
    reviewsCount: 420,
    deliveryEtaMinutes: 30,
    description: "Самые сочные крафтовые бургеры в городе."
  },
  { 
    id: "seller-7", 
    name: "ПиццаФабрика", 
    commissionRate: 0.15,
    logo: "/assets/pizzafabrika/logo.png",
    bannerUrl: "/assets/pizzafabrika/banner.png",
    rating: 4.9,
    reviewsCount: 890,
    deliveryEtaMinutes: 45,
  },
  { 
    id: "seller-8", 
    name: "Грузинский Дворик", 
    commissionRate: 0.15,
    logo: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=150&q=80",
    bannerUrl: "/assets/georgian/banner.png",
    rating: 4.9,
    reviewsCount: 156,
    deliveryEtaMinutes: 50,
    description: "Лучшие хинкали, хачапури и другие блюда грузинской кухни по старинным рецептам."
  },
  { 
    id: "seller-9", 
    name: "Метизыч", 
    commissionRate: 0.10,
    logo: "https://images.unsplash.com/photo-1581147036324-c1e19ca9bbed?auto=format&fit=crop&w=150&q=80",
    bannerUrl: "/assets/metizych/banner.png",
    rating: 4.8,
    reviewsCount: 312,
    deliveryEtaMinutes: 120,
    description: "Всё для строительства, ремонта и обслуживания техники."
  },
  { 
    id: "seller-10", 
    name: "Плазма", 
    commissionRate: 0.10,
    logo: "https://images.unsplash.com/photo-1629131726692-1accd0c53ce0?auto=format&fit=crop&w=150&q=80",
    rating: 4.8,
    reviewsCount: 200,
    deliveryEtaMinutes: 120,
  },
];

export const products: Product[] = [
  {
    id: "food-1",
    sellerId: "seller-1",
    vitrineType: "groceries",
    categoryIds: ["groceries", "dairy"],
    title: "Молоко Простоквашино 3.2%",
    brand: "Простоквашино",
    price: 89,
    oldPrice: 120,
    images: [
      "/assets/proviant/milk.png",
    ],
    unitLabel: "1 л",
    rating: 4.8,
    reviewsCount: 342,
    badge: "-25%",
    inStock: true,
    deliveryEtaMinutes: 15,
    description:
      "Натуральное пастеризованное молоко высшего качества. Произведено из отборного сырья.",
    attributes: { fat: ["high"] },
  },
  {
    id: "food-2",
    sellerId: "seller-2",
    vitrineType: "groceries",
    categoryIds: ["groceries", "bakery"],
    title: "Хлеб Бородинский",
    price: 45,
    images: [
      "/assets/pekarnya/bread.png",
    ],
    unitLabel: "400 г",
    rating: 4.9,
    reviewsCount: 118,
    inStock: true,
    deliveryEtaMinutes: 15,
    attributes: { flour: ["rye"] },
  },
  {
    id: "food-3",
    sellerId: "seller-1",
    vitrineType: "groceries",
    categoryIds: ["groceries", "fruits"],
    title: "Яблоки Гренни Смит",
    price: 159,
    oldPrice: 199,
    images: [
      "/assets/proviant/apples.png",
    ],
    unitLabel: "1 кг",
    rating: 4.7,
    reviewsCount: 51,
    badge: "-20%",
    inStock: true,
    deliveryEtaMinutes: 15,
    attributes: { color: ["green"], package: ["loose"] },
  },
  {
    id: "food-eggs-1",
    sellerId: "seller-1",
    vitrineType: "groceries",
    categoryIds: ["groceries", "dairy"],
    title: "Яйца куриные С0 10шт",
    price: 120,
    images: ["/assets/proviant/eggs.png"],
    unitLabel: "1 пачка",
    rating: 4.8,
    reviewsCount: 231,
    inStock: true,
    description: "Крупные отборные яйца высшей категории.",
    deliveryEtaMinutes: 15,
  },
  {
    id: "food-cheese-1",
    sellerId: "seller-1",
    vitrineType: "groceries",
    categoryIds: ["groceries", "dairy"],
    title: "Сыр Гауда 45%",
    price: 340,
    images: ["/assets/proviant/cheese.png"],
    unitLabel: "200 г",
    rating: 4.9,
    reviewsCount: 164,
    inStock: true,
    description: "Натуральный сыр с приятным мягким вкусом.",
    deliveryEtaMinutes: 15,
  },
  {
    id: "clothes-1",
    sellerId: "seller-3",
    vitrineType: "clothes",
    categoryIds: ["clothes", "tshirts"],
    title: "Футболка базовая белая",
    price: 890,
    oldPrice: 1290,
    images: [
      "/assets/urban_wear/t_shirt.png",
    ],
    unitLabel: "M",
    rating: 4.7,
    reviewsCount: 87,
    badge: "-30%",
    inStock: true,
    deliveryEtaMinutes: 30,
    attributes: { size: ["m"], color: ["white"] },
  },
  {
    id: "tools-1",
    sellerId: "seller-4",
    vitrineType: "tools",
    categoryIds: ["tools", "hand"],
    title: "Молоток строительный",
    price: 349,
    oldPrice: 499,
    images: [
      "/assets/stroyinstrument/a_hammer.png",
    ],
    unitLabel: "500 г",
    rating: 4.8,
    reviewsCount: 23,
    badge: "-30%",
    inStock: true,
    deliveryEtaMinutes: 30,
    attributes: { type: ["hammer"] },
  },
  {
    id: "food-4",
    sellerId: "seller-5",
    vitrineType: "sushi",
    categoryIds: ["rolls"],
    title: "Лава Лайт",
    price: 380,
    images: [
      "/assets/keksberi/lava_lite.png"
    ],
    unitLabel: "1 порция",
    rating: 5.0,
    reviewsCount: 8,
    inStock: true,
    deliveryEtaMinutes: 45,
    description: "Роллы ⭐️\nСостав: Краб,нори,рис,творожный сыр,огурец,соус лава,кунжут 🍚\n*в стоимость не входят:васаби, имбирь и соус*",
  },
  {
    id: "food-5",
    sellerId: "seller-5",
    vitrineType: "sushi",
    categoryIds: ["rolls"],
    title: "Эби Чиз",
    price: 590,
    images: [
      "/assets/keksberi/aby_cheese.png"
    ],
    unitLabel: "1 порция",
    rating: 5.0,
    reviewsCount: 12,
    inStock: true,
    deliveryEtaMinutes: 45,
    description: "🌶️ Острые роллы ⭐️\nСостав: Нори,рис,креветка,творожный сыр,чедер, соус спайси 🌶️\n*в стоимость не входят:васаби, имбирь и соус*",
  },
  {
    id: "food-6",
    sellerId: "seller-5",
    vitrineType: "sushi",
    categoryIds: ["rolls"],
    title: "Чикен Том-Ям",
    price: 440,
    images: [
      "/assets/keksberi/chiken_tomyam.png"
    ],
    unitLabel: "1 порция",
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    deliveryEtaMinutes: 45,
    description: "Роллы 🔥\nСостав: нори, рис,соус «том ям», курица, болгарский перец, кунжут,творожный сыр,масага ✨\n*в стоимость не входят:васаби, имбирь и соус*",
  },
  {
    id: "food-7",
    sellerId: "seller-5",
    vitrineType: "sushi",
    categoryIds: ["rolls"],
    title: "Киото 🔥",
    price: 400,
    images: [
      "/assets/keksberi/kioto.png"
    ],
    unitLabel: "1 порция",
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    deliveryEtaMinutes: 45,
    description: "🔥 Острые роллы ⭐️\nСостав: Нори, рис, тунец,огурец, творожный сыр, соус шрирача 🌶️\n*в стоимость не входят: васаби, имбирь и соус*",
  },
  {
    id: "food-8",
    sellerId: "seller-5",
    vitrineType: "sushi",
    categoryIds: ["rolls"],
    title: "Кунсей",
    price: 850,
    images: [
      "/assets/keksberi/kynsei.png"
    ],
    unitLabel: "1 порция",
    rating: 0,
    reviewsCount: 0,
    inStock: true,
    deliveryEtaMinutes: 45,
    description: "Роллы ⭐️\nСостав: Нори, рис, творожный сыр,чука,лосось, креветка 🍣\n*в стоимость не входят:васаби, имбирь и соус*",
  },
  {
    id: "ready-1",
    sellerId: "seller-2",
    vitrineType: "ready_food",
    categoryIds: ["ready_food", "soups"],
    title: "Борщ с говядиной",
    price: 180,
    images: ["/assets/pekarnya/borcsh.png"],
    unitLabel: "300 г",
    rating: 4.6,
    reviewsCount: 30,
    inStock: true,
    deliveryEtaMinutes: 15,
    description: "Наваристый борщ по домашнему рецепту. Только разогреть!",
  },
  {
    id: "ready-2",
    sellerId: "seller-2",
    vitrineType: "ready_food",
    categoryIds: ["ready_food", "second_courses"],
    title: "Пюре с котлетой",
    price: 210,
    images: ["/assets/pekarnya/mash.png"],
    unitLabel: "350 г",
    rating: 4.8,
    reviewsCount: 50,
    inStock: true,
    deliveryEtaMinutes: 15,
    description: "Классическое картофельное пюре с домашней мясной котлетой.",
  },
  {
    id: "pizza-1",
    sellerId: "seller-7",
    vitrineType: "pizza",
    categoryIds: ["pizza"],
    title: "Вок",
    price: 1009,
    images: ["/assets/pizzafabrika/pizza_wok.png"],
    unitLabel: "760 г",
    rating: 4.9,
    reviewsCount: 200,
    inStock: true,
    deliveryEtaMinutes: 40,
    description: "Соус ранч, соус сладкий чили, моцарелла, куриное филе, помидоры, овощи вок (цукини, болгарский перец, лук порей), базилик сушеный.",
  },
  {
    id: "pizza-2",
    sellerId: "seller-7",
    vitrineType: "pizza",
    categoryIds: ["pizza"],
    title: "Том ям с курицей",
    price: 1029,
    images: ["/assets/pizzafabrika/tomyam.png"],
    unitLabel: "850 г",
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
    deliveryEtaMinutes: 40,
    description: "Соус том ям, моцарелла, куриное филе, шампиньоны, рисовые шарики том ям, помидоры черри, кокосовое молоко, кинза.",
  },
  {
    id: "pizza-3",
    sellerId: "seller-7",
    vitrineType: "pizza",
    categoryIds: ["pizza"],
    title: "Батя",
    price: 999,
    images: ["/assets/pizzafabrika/batya.png"],
    unitLabel: "930 г",
    rating: 5.0,
    reviewsCount: 384,
    inStock: true,
    deliveryEtaMinutes: 40,
    description: "Соус фирменный, моцарелла, бекон, охотничьи колбаски, шампиньоны, картофель беби, маринованные огурцы, лук криспи, соус сырный чили, зелень.",
  },
  {
    id: "georgian-1",
    sellerId: "seller-8",
    vitrineType: "georgian",
    categoryIds: ["hot_dishes"],
    title: "Хинкали с говядиной и свининой",
    price: 350,
    images: ["/assets/georgian/khinkali.png"],
    unitLabel: "5 шт",
    rating: 5.0,
    reviewsCount: 85,
    inStock: true,
    deliveryEtaMinutes: 50,
    description: "Тонкое тесто, много сочного мяса и ароматных специй. Подаются горячими.",
  },
  {
    id: "tools-1",
    sellerId: "seller-9",
    vitrineType: "tools",
    categoryIds: ["tools", "hand_tools"],
    title: "Набор отверток профессиональный",
    brand: "PlazmaTech",
    price: 1250,
    images: ["/assets/metizych/screwdrivers.png"],
    unitLabel: "1 наб.",
    rating: 4.8,
    reviewsCount: 34,
    inStock: true,
    description: "Набор из 12 отверток с магнитным наконечником и прорезиненными ручками.",
  },
  {
    id: "tools-2",
    sellerId: "seller-9",
    vitrineType: "tools",
    categoryIds: ["tools", "power_tools"],
    title: "Дрель ударная 800Вт",
    brand: "PlazmaPro",
    price: 4500,
    oldPrice: 5200,
    images: ["/assets/metizych/drill.png"],
    unitLabel: "1 шт.",
    rating: 4.9,
    reviewsCount: 120,
    inStock: true,
    description: "Надежная ударная дрель для работ по бетону и кирпичу.",
  },
  {
    id: "component-1",
    sellerId: "seller-9",
    vitrineType: "components",
    categoryIds: ["components", "washing_machine"],
    title: "Насос сливной для стиральной машины",
    brand: "Askoll",
    price: 950,
    images: ["https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.7,
    reviewsCount: 15,
    inStock: true,
    description: "Универсальный сливной насос (помпа) Askoll 40 Вт.",
  },
  {
    id: "component-2",
    sellerId: "seller-9",
    vitrineType: "components",
    categoryIds: ["components", "fridge"],
    title: "Терморегулятор для холодильника",
    brand: "PlazmaTech",
    price: 650,
    images: ["/assets/metizych/thermostat.png"],
    unitLabel: "1 шт.",
    rating: 5.0,
    reviewsCount: 8,
    inStock: true,
    description: "Универсальный терморегулятор К-59.",
  },
  {
    id: "tech-1",
    sellerId: "seller-10",
    vitrineType: "electronics",
    categoryIds: ["electronics", "gadgets"],
    title: "Фен профессиональный",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.7,
    reviewsCount: 15,
    inStock: true,
    description: "Мощный фен с несколькими режимами и ионизацией.",
  },
  {
    id: "tech-2",
    sellerId: "seller-10",
    vitrineType: "electronics",
    categoryIds: ["electronics", "gadgets"],
    title: "Электронные часы LED",
    price: 1200,
    images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.5,
    reviewsCount: 8,
    inStock: true,
    description: "Настольные часы с будильником и термометром.",
  },
  {
    id: "tech-3",
    sellerId: "seller-10",
    vitrineType: "electronics",
    categoryIds: ["electronics", "accessories"],
    title: "Зарядное устройство Type-C",
    price: 800,
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.9,
    reviewsCount: 42,
    inStock: true,
    description: "Быстрая зарядка 20W для смартфонов и планшетов.",
  },
  {
    id: "tech-4",
    sellerId: "seller-10",
    vitrineType: "electronics",
    categoryIds: ["electronics", "gadgets"],
    title: "Видеокамера Action Pro",
    price: 15000,
    images: ["https://images.unsplash.com/photo-1560060141-7b9018741cb7?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.8,
    reviewsCount: 22,
    inStock: true,
    description: "Экшн камера с поддержкой 4K и защитой от воды.",
  },
  {
    id: "tech-5",
    sellerId: "seller-10",
    vitrineType: "electronics",
    categoryIds: ["electronics", "gadgets"],
    title: "Электробритва мужская",
    price: 4500,
    images: ["https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.6,
    reviewsCount: 19,
    inStock: true,
    description: "Беспроводная электробритва с плавающими головками.",
  },
  {
    id: "tech-6",
    sellerId: "seller-10",
    vitrineType: "electronics",
    categoryIds: ["electronics", "gadgets"],
    title: "Механические часы Classic",
    price: 8500,
    images: ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=60"],
    unitLabel: "1 шт.",
    rating: 4.9,
    reviewsCount: 55,
    inStock: true,
    description: "Стильные механические часы с кожаным ремешком.",
  },
];
export const filterConfig: Record<string, VitrineFilterConfig> = {
  groceries: {
    categories: [
      {
        id: "dairy",
        label: "Молочные продукты",
        attributes: [
          { id: "fat", label: "Жирность", options: [{ id: "low", label: "Обезжиренное" }, { id: "high", label: "Жирное" }] },
        ],
      },
      {
        id: "bakery",
        label: "Хлеб и выпечка",
        attributes: [
          { id: "flour", label: "Мука", options: [{ id: "wheat", label: "Пшеничная" }, { id: "rye", label: "Ржаная" }] },
        ],
      },
      {
        id: "fruits",
        label: "Фрукты",
        attributes: [
          { id: "color", label: "Цвет", options: [{ id: "green", label: "Зеленые" }, { id: "red", label: "Красные" }] },
          { id: "package", label: "Упаковка", options: [{ id: "loose", label: "На развес" }, { id: "packed", label: "Фасованные" }] },
        ],
      },
      { id: "drinks", label: "Напитки" }
    ],
  },
  ready_food: {
    categories: [
      { id: "soups", label: "Супы" },
      { id: "second_courses", label: "Вторые блюда" },
      { id: "salads", label: "Салаты" }
    ],
  },
  sushi: {
    categories: [
      { id: "sushi", label: "Суши и роллы" }
    ],
  },
  burgers: {
    categories: [
      { id: "beef", label: "С говядиной" },
      { id: "chicken", label: "С курицей" }
    ],
  },
  pizza: {
    categories: [
      { id: "meat", label: "Мясная" },
      { id: "cheese", label: "Сырная" }
    ],
  },
  georgian: {
    categories: [
      { id: "khinkali", label: "Хинкали" },
      { id: "khachapuri", label: "Хачапури" }
    ],
  },
  clothes: {
    categories: [
      {
        id: "tshirts",
        label: "Футболки",
        attributes: [
          { id: "size", label: "Размер", options: [{ id: "s", label: "S" }, { id: "m", label: "M" }, { id: "l", label: "L" }] },
          { id: "color", label: "Цвет", options: [{ id: "white", label: "Белый" }, { id: "black", label: "Черный" }] },
        ],
      },
    ],
  },
  tools: {
    categories: [
      {
        id: "hand",
        label: "Ручной инструмент",
        attributes: [
          { id: "type", label: "Тип", options: [{ id: "hammer", label: "Молотки" }, { id: "screwdriver", label: "Отвертки" }] },
        ],
      },
    ],
  },
  electronics: {
    categories: [
      { id: "gadgets", label: "Гаджеты и техника" },
      { id: "accessories", label: "Аксессуары" }
    ],
  },
};

